### ISSUE TITLE
Couldn't detect steam shortcuts file.

### ISSUE THREAD

**Issue by Thebombuknow** [Alia5/GloSC#118]
I keep getting that error, and I do have multiple non-steam games added. Is it an issue with my steam install being a drive other than the C drive?

**Comment by Yoshimit** [comment]
I think GloSC only add to steam works if running as admin (and Steam too).
I have this same problem

**Comment by Thebombuknow** [comment]
I've tried running both as admin as well.

**Comment by dimmuboy** [comment]
I have same problem but GloSC and Steam are installed on same C drive. Running as admin does not solve this problem.

**Comment by Thracky** [comment]
For starters Steam MUST be running when you go to add shortcuts to Steam. This is because GloSC relies on a registry key that is only set when Steam is running and logged in to locate your shortcuts file.

If that still doesn't resolve it, verify the following:
* Open regedit and go to HKEY_CURRENT_USER\Software\Valve\Steam
  * SteamPath should be set to wherever you have steam installed.

* Then open HKEY_CURRENT_USER\Software\Valve\Steam\ActiveProcess
  * Look at the value of "ActiveUser", you should see a hexadecimal value 0x<something> with the decimal value in brackets ()
  * Go to your steam install directory then "userdata" and you should see a numeric directory in there the same as the decimal value of ActiveUser.

**Comment by soularis3224** [comment]
I had the same issues (Steam running, run GloSC as admin, both installed to the same drive).

SteamPath was correct, however ActiveUser was set to 0 (I'm fairly sure Steam was running at the time). I hadn't noticed any other weird side effects from this value not being set previously.

I updated it to match the "userdata" id number, restarted Steam and GloSC, and GloSC was able to add shortcuts. Forza Horizon 4 is now working correctly, and the issues I'm having with Burnout Paradise appear to be unrelated.

**Comment by Thracky** [comment]
Closing this issue as it seems resolved.
