### ISSUE TITLE
Couldn't detect steam shortcuts file, failed to hook steam errors

### ISSUE THREAD

**Issue by ParcelRot** [Alia5/GloSC#3]
Hello. When I add an Instance (Kodi 17 in this case) and then click Add to Steam, I get this error:

![image](https://cloud.githubusercontent.com/assets/15962029/20863753/d165f666-b992-11e6-9a6e-ff241e9c9763.png)

I have steam installed and is the latest version. However, I did copy steam from a previous windows install, into C:\Steam. I did reinstall steam into that directory afterwards when I got the error from GloSC, but still the same result!

When I manually add the Kodi.exe into my steam Library, I get the cannot hook steam error in the console:
![image](https://cloud.githubusercontent.com/assets/15962029/20863765/66fb4ee2-b993-11e6-9cd4-45bab51fdf5c.png)

Unfortunately, the steam controller still doesn't work - nothing happens when I touch any of the buttons or controls.

I am running latest Windows 10 Anniversary 64 bit with the most recent updates.

This is with GloSC version 1.1.0. I haven't tried an earlier version yet.

**Comment by Alia5** [comment]
1. Did you have any non-Steam shortcuts added before? If yes, Steam probably doesn't create that file if there aren't any. Will be fixed before the next release, then.

2. I'm aware that some people have issues with the Steam hook.
I don't really understand why, though, since it works for me on a freshly installed VM with nothing on it other than Steam and GloSC - Need more info on this.

**Comment by Alia5** [comment]
@ParcelRot As far as hooking goes, could you try this one here?

[GloSC-PreRel_x64](http://wtf.flatspot.pictures/glosc/GloSC-installer_x64.exe)

**Comment by ParcelRot** [comment]
Thanks for looking into it - it's rather strange! Steam shortcuts started working again - I'm not sure why. If Steam isn't running it doesn't work, but when Steam is running it works now. Odd, because I was sure I had it running before. Oh well, no big deal now!

Sure, I'll try that!

**Comment by Alia5** [comment]
Ouh, yeah it only works when Steam is actually running, forgot about that

I'm getting the currently logged on user via the windows registry, instead of modifying the shortcuts file of every user that has ever been logged on on the system (like others)

I prob. should be more clear about this, though...

**Comment by ParcelRot** [comment]
Hey this time it hooks! Thanks! :)
