### ISSUE TITLE
Repeated Unavoidable Notifications [Windows 10]

### ISSUE THREAD

**Issue by grayvyn** [Alia5/GloSC#34]
Hello,

Every time I launch a game it's giving me some notifications that are a severe nuisance and prevent me from doing anything until the notifications go away.

The first one that pops up says "Installing virtual xbox controller"
the second one that pops up confirms its installation:
![image](https://user-images.githubusercontent.com/22518281/33453724-45b209e0-d5dc-11e7-8d3a-575396e438c2.png)

The problem here is that the popup happens continuously, like 10+ times one after another (ding ding ding ding ding ding... you get the point), and when the second message appears, it also happens continuously.

**Comment by Alia5** [comment]
They should only appear the first time you are launching something.

Secondly: Enable XBox configuration support in Steams controller options, otherwise, GloSC creates four controllers -> You getting more notifications.

Other than that: The notifications are due to [ViGEm](https://github.com/nefarius/ViGEm/issues)
I am unsure, though, if anything can even be made to prevent the popups (one time, that is)
