### ISSUE TITLE
Overlay program launching but cannot be summoned over game with SHIFT+TAB.

### ISSUE THREAD

**Issue by Dasnap** [Alia5/GloSC#39]
Example game: Fortnite

Settings:

[X] Enable Overlay

[X] Enable Virtual Controllers

[_] Use Desktop Config

[X] Launch Game: C:\Program Files\Epic Games\Fortnite\FortniteGame\Binaries\Win64\FortniteClient-Win64-Shipping.exe

[_] Close shortcut when launched Application closes (Disable for Uplay-games!)

![image](https://user-images.githubusercontent.com/16799832/35492304-160d44a6-04a4-11e8-94d2-0cb78946ecde.png)

Result: The overlay 'window' launches (the 'press SHIFT+TAB' message appears in the corner as expected), but when the actual game launches (in borderless windowed), pressing SHIFT+TAB does not bring the overlay up. I can ALT+TAB to click on the GloSC window again, which then makes it appear transparent over the game, but then clicking the game again makes the overlay disappear and cannot be summoned correctly again. 

Could this be due to how the Epic Launcher works?

A Reddit user seemed to have success with the same settings so it may be inconsistent. https://www.reddit.com/r/FortNiteBR/comments/72vmrd/how_to_add_game_to_steam/dpw0kvw/

Edit: So I've been testing some more and this seems to be an issue with every game I've tried. The only way to bring up the desktop overlay with SHIFT+TAB is to click on the separate overlay window first. Clicking back onto the game again then takes away this ability.

**Comment by Alia5** [comment]
The problem here is that the overlay itself listens for that particular hotkey, but only **if** the hooked process is currently in focus.

You can, however, just use the Steam (or Guide) button on your controller.

**Comment by Dasnap** [comment]
So is there no effective way to get this working in a keyboard and mouse setup? I wanted to use it in desktop mode so I could get quick access to Steam chat and notifications and such.

**Comment by Nichodeamus** [comment]
I have exactly the same problem.   Firstly, I'd just like to say that the overlay windows IS present over the top of the game window...  And the reason I know that, is because when I first tried using it, my framerate display from RTSS was hooking into both the game's window and the overlay window, giving me TWO displays of my framerate...  But although the overlay window is present, it ignores all keyboard input unless it is selected as the active window.  Meaning, of course, that any overlay shortcut keys you have setup in steam do not work, without first using Alt-tab to switch to the overlay window...  Which kindof defeats the whole purpose of having an overlay window.

**Comment by Alia5** [comment]
Built in a little hack to accomplish this:
3cf635498bc6dcebfae715f8e2da81556a360fb8

Additionaly overlay was sorta broken anyway... Fixed here: https://github.com/Alia5/GloSC/commit/06d5a6d34b3e7f2891e5744a58d571469ee5df5a
