### ISSUE TITLE
GloSC screws up all Steam SC's profiles

### ISSUE THREAD

**Issue by pimpace** [Alia5/GloSC#4]
As I wanted to play Uplay games over Steam overlay with my Steam Controller, at certain circumstances it can't be done only with adding non-steam game to the Steam library known by the fact which is the purpose of your program. So this is when your application comes in.

But after I started to use it, I got weird behavior. I saved some profile in Steam for controller settings, as such desktop, BPM and even the game what I play with. The wrong behavior is that when I don't load GloSC shortcut (default, global settings with no game lauching so it attaches on desktop with steam running in background) my controller goes crazy and left joystick get some weird "phantom" input as constantly getting right movement input. Also when I pulling left trigger, left joystick resets its position then starts moving right direction as I'm pulling the trigger. In this case from now on without GloSC running SC is unusable due to this constant left joy "phantom" input.

I've tried to delete all my Steam-controller configs both in local and Steam-cloud with no success. Also I've tried to "trimmer" left joy with Dead Zone setting, also with no success. 

I'm using 1.1.2 version of GloSC, and I've tried even uninstalling it both GloSC and Virtual Gamepad Emulation Driver. No success. As far as turn on my controller this constant wight movement "activated" and I cannot use my controller. 

Is this a bug? Or did I screwed up something? Where are the settings of your application? Or its registry settings I can delete/reset to prevent this behavior?
I think, it's do with gamepad emulation because when I click dpad-up, all my sound in game gets muted, as you've mentioned in your FAQ that due to Xbox360 emulation (or PS4 controller, don't remember) it acts as if it control media player so default playing device is chaning with dpad-up. It can easily fixed by change this back in playback devices. 

However the phantom leftjoy input still happens all the time.

What should I do?

**Comment by Alia5** [comment]
GloSC doesn't fuss with the Controller itself. 
If there are problems, in a worst case scenario all you'd have to do is close the GloSC-Shortcut and maybe even restart Steam. If that doesn't help - GloSC did not cause the issue.

I'd recommend recalibrating the controller via Steam BPM.
If problems still occur I'd guess you have a dirty touchpad (no srsly...) *or* the SC itself is just broken.

**Comment by pimpace** [comment]
Thanks Man. You should know, that faaaar from it that I blame you. As I'm a developer too, I know exactly how many circumstances we should watch and handle. 
All the investigation, read all the stuff about your application, settings, configs, I came up with my SC is probably broken. :( I don't no if it could be dirty, or dusty inside the case at the left analog joy... donno, really. I hoped it cannot be broken due to I have it since just over a year. But sadly seems to... :( I've contacted Steam and the distributor I've purchased from but I doubt they would help me or replace my shit.

On the other case, until my SC broken I've tested your app very much and I liked it! Worked as intended. However, the only thing you should solve the overlay behind the target program/game while it's in full screen. I understand while you hook through Steam you attached your app on desktop that's why it can bring overlay if the game is in borderless full window only. But as Steam could do this, I believe you can too if you get independent from Steam.

Keep it up Man, did a very good job!

**Comment by Alia5** [comment]
Getting the overlay to work through GloSC in fullscreen applications is a won't-fix.
If there are no problems hooking the DX / OpenGL -Window, (Steamoverlay , wich also does most of the controller-stuff ;) ) why even bother using GloSC, instead of adding the application to Steam directly?

Going Steam independent is something I also don't want to do. I'd like to keep their excellect configurator.
There is, however [https://github.com/ynsta/steamcontroller](a standalone SteamController), (in python for whatever reason). AFAIK it does currently only work on Windows, but it's OSS anyway...

**Comment by pimpace** [comment]
Ok.

IMHO your application is better than Standalone SC.

And for your question? What is the reason why don't you just use "adding non-steam game to your library"?
Because you cannot use your SC with other game clients's games.
For example, I searched a solution I can able to play Uplay's Watch Dogs 2. This games has a multiplayer anti-cheat system which senses Steam overlay and Steam hook (which needed due to reach all the functionality to SC) as a cheat. LOL
In this case even you add this game to Steam, overlay will be disabled so game wont recognize the SC.

Again; LOL. Uplay is stupid.

And what is shame, they no seem to will to change this. So this is when your app comes in. Yes, maybe it wouldn't be separate from Steam. Steam is a good client. But the best would be if your app could attached a non-Steam fullscreen-mode game and able to show steam-overlay.
Technically during my tests, it seemed it is always attached to the desktop, not to the game itself as Steam does with a Steam-game. I never achieved to setup your app in any other way, but it worked even when I set the game to fullscreen mode. Even your app attached through Steam to the desktop, Uplay recognise my SC as an Xbox360 controller and through Steamoverlay I can reach all my SC's functionality. 

I thought you created your app such an situations.... :)

**Comment by Alia5** [comment]
> Steam overlay and Steam hook (which needed due to reach all the functionality to SC) as a cheat. LOL

That's exactly the thing.
To get any kind of overlay in any game, we'd need to hook it. - That's what Steam already does.
If Steam can't hook into it, then why should I be able to do so? Without hooking, no fullscreen overlay.
No way around.

Use borderless window mode + GloSC if you need an overlay so badly.

Okay so here's a basic breakdown of how GloSC actually works:
A single GloSC-target "fakes" beeing a game. It uses a transparent, click through OpenGL rendered window for this.

When launched via Steam, a GloSC-Target gets hooked from Steam and from now on sees the "fake XInput inputs" Steam sends via the overlay.
(Steam also gets hooked from GloSC to ensure that shortcuts specific controller profile, instead of the Desktop one, even if you switch applications, but that's not important to the overlay-stuff)

GloSC then takes every one of those XInput inputs and forwards them to a **windows kernel driver** ([https://github.com/nefarius/ViGEm](ViGEm)) which does the rest of the controller related magic.
Now, every single application on the computer sees an XBox360-controller connected - why the controller works for fullscreen applications, the overlay doesn't, and (via GloSC) never will.

Now before this goes any more OT - closed
