### ISSUE TITLE
"Github issues are for code issues, not for user support, therefore - closed"

### ISSUE THREAD

**Issue by joe7dust** [Alia5/GloSC#58]
So where do we go for user support? I've never seen a niche program like this where the developer doesn't answer the email that he has listed. Sent 2 already, first one was even before I posted the 2nd issue.

'So where else can I go for support for this niche product that you created? I don't take to github lightly, not sure why so evasive. There literally is no option in steam to do what you described. When you go to create a custom bind in their config they present you with a picture of mouse and keyboard and there are no ways to simulate a gamepad button through there. Besides even if there were, I don't see how that would be effective given this works by emulating a virtual 360 controller which doesn't have paddles and which verifies that the paddles and X/A send identical signals to the OS...'

**Comment by nefarius** [comment]
How about the Discord server listed in the README? And yes, the GitHub issue tracker is *not* a helpdesk. So you already sent two mail; so what? You got a support contract? No? Maybe @Alia5 has a life outside of this **free** project, have you ever thought about that? Of course you haven't. Posts like these contribute to open-source projects dying because the author gets starved of the fun investing in it. Did I mention this project is free of charge? Bloody hell...
