### ISSUE TITLE
Support launch arguments

### ISSUE THREAD

**Issue by rockmacaca** [Alia5/GloSC#6]
I've found that GloSC works as a mostly painless solution to problems with Steam link <--> emulators in terms of properly exposing controllers. However, there isn't any way I can pass the command line arguments needed to properly launch game titles.

I've peeked around and this didn't look too hard to add, so support for this soon would be very nice.

P.S. I've been trying to build this myself, but I'm getting
```
The procedure entry point vigem_target_set_vid could not be located in the dynamic link library C:\Program Files\GloSC\...
```
when I run a SteamTarget.exe copy. Any help there?

**Comment by Alia5** [comment]
Regarding your ViGEm Problem:
Install the **newest** available version of [ViGEm](https://github.com/nefarius/ViGEm)
**And** use the correct version ViGEmUM.dll out of GloSCs dependencies folder (x86 / x64) for your **build type**.
I haven't played with 32bit builds all too much, although they should work.
I'd recommend building x64 and using x64 libs

Also, link to the correct version, but that should already be setup properly in the project files.


Regarding launch arguments:
"I've peeked around and this didn't look too hard to add, so support for this soon would be very nice."
Feel free to submit a PR ;)
I'll look into it **if** I get the time for it, though

**Comment by rockmacaca** [comment]
By the way, I got it built fine, thanks :). I had to get the VS Qt plugin and it modified some project files when I set the version, is that normal?

Also, I'm guilty of this too with small solo projects like these, but I wish some things were commented/documented a bit better. In particular I was curious of what the rationale behind the existence of GloSC_GameLauncher was? I could only make out that it's just polling a block of shared memory for a program name to launch, it seems like most of its functionality could be easily included inside SteamTarget?

I was curious since ideally I'd prefer if the spawned process closed when a launched SteamTarget instance exits (which typically happens through "Exit shortcut" in the overlay). Since a SteamTarget instance has basically no idea how to reach the program it launched through GloSC_GameLauncher, implementing this doesn't seem trivial.

Sorry for all the questions, but I just want to make sure I know what's going on before I start making significant changes!

**Comment by Alia5** [comment]
Setting up the Qt version, and getting the Qt plugin, yes, totally normal business when using Qt and VS.
Setting Qt version even is included in the build guide. The Qt-Plugin, however, is not. I'll fix that

It has two purposes mainly.
1. If you launch a game, from a child process of Steam (the SteamTarget), Steam *also* injects the overlay in the then launched process.
(In case you're interested: Dynamic process forking the hacky Win32 way doesn't work...)
I could get around this by more hooking of Steam, but I want to keep this to a minimum or ideally get rid of that completely.

2. It acts as a safeguard for ejecting my .dll and unhooking Steam in case the Target process gets killed unexpectedly.

Reason 1 is somewhat briefly stated in the Readme and reason 2 a but in the build and installation guide.

It is totally possible to close the launched game from SteamTarget, though.
However, if the SteamTarget gets closed unexpectedly, you may or may not receive the close or similar event callbacks from the OS.
The way to go would be to implement this in the GloSC_GameLauncher too, or at least provide a second "safeguard", as it can easily provide that functionality since it's an "external" program, in which Steam doesn't have its fingers in.

In any case, I agree that there are *some* documentation needs for when other developers wanna chime in, although it really is a pretty small and mostly straightforward project, at least once you actually play with it. On the not so straight-forward stuff like the Steam hook, overlay messages, and so on, I hope I did enough in the comments and [in this blogpost](https://behind.flatspot.pictures/third-party-steam-controller-software-part2-my-take-on-it/)


I think that's enough OT for now, you can directly shoot me a mail or find me someplace else on the Internet if there are any more questions.
