### ISSUE TITLE
GloSC 1.1.2 does not work with Steam Client Mar 9 2017 version.

### ISSUE THREAD

**Issue by siratama** [Alia5/GloSC#7]

**Comment by Alia5** [comment]
It's been fixed in the source for a long time now.
I won't push out a new release until a ViGEm update with an installer is out, as Steams support for other controllers than the SC messed stuff up a bit more, and the newer versions of ViGEm provide an easy fix for that. (Also, already implemented in the source...)

**Comment by 8Keep** [comment]
Do I have to build vigem too or just use the latest release of vigem?

**Comment by rockmacaca** [comment]
@8Keep Either of the x86 or x64 DLLs hosted in this repo will work once you copy the correct one to the working directory. You also need to install the latest bus driver [here](https://github.com/nefarius/ViGEm/releases). There's no installer, so you can either right click the .ini -> Install or update through Device Manager.

**Comment by 8Keep** [comment]
This is too complex for me. Id like to be able to use this so I can play dolphin emulator games with the steam controller, ill just wait until the next update

**Comment by Alia5** [comment]
Use latest pre-release.
