### ISSUE TITLE
Certain UWP games don't show in the program.

### ISSUE THREAD

**Issue by ValiantBlade** [Alia5/GloSC#86]
I've noticed that some of the UWP games I have installed, namely Opus Magnum and Wizard of Legend, don't show up in GloSC's UI.

**Comment by Thracky** [comment]
So the issue here appears to be the way that UWP packages are listed, by relying on registry entries listed in HKEY_CLASSES_ROOT\Extensions\ContractId\Windows.Launch\PackageId. This does seem to miss a number of the newer games such as Outer Worlds and obviously those you've mentioned as well.

I think the solution is to use the PackageManager class here: https://docs.microsoft.com/en-us/uwp/api/windows.management.deployment.packagemanager , more specifically the FindPackages() method https://docs.microsoft.com/en-us/uwp/api/windows.management.deployment.packagemanager.findpackages.

I'm playing around with it and if I manage to get something working I'll submit a PR, but anyone else is welcome to make an attempt :)

**Comment by brainseed** [comment]
For what it's worth, I am having similar issues with a couple games. The search doesn't find The Outer Worlds or Mutant Year Zero.

**Comment by Hardtarget24** [comment]
ah shoot was trying to use this to play The Outer Worlds and sure enough it's not there.

Hope there's a fix :\

**Comment by brainseed** [comment]
> ah shoot was trying to use this to play The Outer Worlds and sure enough it's not there.
> 
> Hope there's a fix :\

I worked around it by using suggestions in this thread: https://www.reddit.com/r/SteamController/comments/bz78ig/quick_workaround_for_game_pass_games_windows/

You can just paste the package name into the box instead of hitting the UWP button. I was trying to get everything working via Steam Link and had to eventually give up because the games would launch on my desktop but would not appear in steam link.  However, if I was sitting at my desktop everything worked fine using the methods in the thread above.  Good luck!

**Comment by Hardtarget24** [comment]
aww the whole point was to try to get it working in steam link! lol

**Comment by brainseed** [comment]
Yeah I was able to get some games to function (Ori in the Blind Forest) but I just could not get Outer Worlds or Mutant Year Zero to appear. Really frustrating because it was very close.

**Comment by Thracky** [comment]
FWIW this powershell snippet should give you the package name followed by the App ID (replace `<gamename>` with whatever you're searching for):

`Get-AppxPackage -Name "*<gamename>*" | foreach {echo $_.PackageFamilyName $_ | Get-AppxPackageManifest | Select-Xml -XPath "//blah:Application" -Namespace @{blah="http://schemas.microsoft.com/appx/manifest/foundation/windows10"} | foreach {$_.Node.getAttribute("Id")}}`

Then for your path in GloSC you would do package name!App Id.

**Comment by petetnt** [comment]
Thanks @Thracky for that, I simplified that to the following which worked for me:

```
$Game="<gamename>";"$(Get-AppPackage -Name "*$Game*")!$((Get-AppxPackage -Name "*$Game*" | Get-AppxPackageManifest).package.applications.application.id)"
```
